### ISSUE TITLE
error status code 504 after fresh start 

### ISSUE THREAD

**Issue by YuriyGavrilov** [pinterest/querybook#1331]
Hi Team! 

Just wished to try Querybook by quick start guide 

`git clone https://github.com/pinterest/querybook.git
cd querybook`

`make `

get an error ModuleNotFoundError: No module named 'langchain' in loop in console. 

in the web getting error 

Unexpected Authentication Error
Request failed with status code 504

What's wrong with it?

**Comment by jczhong84** [comment]
Hey Yuriy,
It's because we added LLM features recently, but forgot to make the dependencies correct. 
Please add `-r ai/langchain.txt` to your `requirements/local.txt` as a workaround for now. we'll have a fix soon.

**Comment by YuriyGavrilov** [comment]
will test it now. Create new file `requirements/local.txt` and add `-r ai/langchain.txt`
Many thx!

**Comment by jczhong84** [comment]
just had a fix for it #1333

**Comment by YuriyGavrilov** [comment]
@jczhong84 great job thx 🙏
