### ISSUE TITLE
Not able to see my snowflake tables in tables tab

### ISSUE THREAD

**Issue by goelrohan6** [pinterest/querybook#488]
I added a new metastore with loader type as
![image](https://user-images.githubusercontent.com/14099191/113184792-43200b80-9273-11eb-8178-b945bcc04767.png)

connection string as - `snowflake://user:pass@abc.ap-south-1/COVID19_JHU?warehouse=COMPUTE_WH`

Added update schedule and ran it a few times
![image](https://user-images.githubusercontent.com/14099191/113184928-68147e80-9273-11eb-80d5-221e0eabd411.png)

But when I go in my environment I'm still seeing the demo tables
![image](https://user-images.githubusercontent.com/14099191/113184961-76fb3100-9273-11eb-9246-92a2b49eb942.png)

In cmd K search too, i'm seeing just the demo metastore, what I'm I doing wrong here ?
![image](https://user-images.githubusercontent.com/14099191/113185014-8a0e0100-9273-11eb-87ea-6f84a39a86ef.png)

**Comment by czgu** [comment]
Hi, you would need to assign a metastore to a query engine for it to show up. The relationship is as followings:

(Snowflake)                                                   
Environment <*-*> QueryEngine <*-1> QueryMetastore

**Comment by goelrohan6** [comment]
aaah, I see, thanks a lot it worked 🎊
