### ISSUE TITLE
Permission denied Errors  while starting up querybook

### ISSUE THREAD

**Issue by chandmk** [pinterest/querybook#489]
redis_1          | 1:M 01 Apr 2021 13:34:58.749 * Ready to accept connections
scheduler_1      | bash: ./querybook/scripts/runservice: Permission denied

querybook_web_1 exited with code 126
web_1            | bash: ./querybook/scripts/bundled_docker_run_web: Permission denied

OS: CentOS

**Comment by czgu** [comment]
Hi @chandmk, unfortunately, querybook has never been tested on CentOS before but it does work on Ubuntu. Can you double-check if you have execute permission for both of these bash files?

I checked the git files and they are marked as executable here:
% git ls-files --stage
100755 6509774b50721b19a770956d30042866b568a722 0       bundled_docker_run_web
100755 9459a321a0d5825f86bcc4c79a712dd8c46c4778 0       docker_run_interactive
100755 a6656b6bf30fc2c22bdce6deef0ddb4e4221e63e 0       init_db
100755 baefbdc46a4b9ac8d3757c2b1f4bd0deaed2aac8 0       run_test
100755 6f61735555de053f432aedd3d8f574b4ab61ec6a 0       runservice

**Comment by chandmk** [comment]
Later I realized that that setup was tested only on ubuntu and I switched to it.
