### ISSUE TITLE
Increase elasticsearch max file descriptors

### ISSUE THREAD

**Issue by wyllie2** [pinterest/querybook#493]
I tried to create a pull request for this but I got a permission denied...

I ran into this issue while doing the simple build on a fresh AWS EC2 running Amazon Linux.  The first error I got referred to a container being unhealthy.  I tracked this down to an error in the elasticsearch container:
```
max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536] 
```

The fix is to explicitly define the max number of file descriptors in the docker-compose.yml file
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 79bcba0..9db49e0 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -127,6 +127,9 @@ services:
             memlock:
                 soft: -1
                 hard: -1
+            nofile:
+                soft: 65536
+                hard: 65536
         volumes:
             - esdata1:/usr/share/elasticsearch/data
         ports:
```

I added this and it now works on my EC2 running Amazon Linux as well as on MacOS

**Comment by czgu** [comment]
Thanks for catching it. I will update the limit on the docker file, test it on ubuntu/mac and submit a PR.
Just for future references, you can open a pull request by forking the repo and submit from there.
