### ISSUE TITLE
Add plugin for Trino

### ISSUE THREAD

**Issue by bitsondatadev** [pinterest/querybook#509]
For those that don't know [there was a split in the Presto community 2 years ago, and the Presto creators are now working on a fork of Presto called Trino (formerly known as PrestoSQL)](https://trino.io/blog/2020/12/27/announcing-trino.html). We want to also include Trino in the list. 

There is not much change needed from the [existing Presto executor](https://github.com/pinterest/querybook/blob/master/querybook/server/lib/query_executor/clients/presto.py) from what I can tell, you would simply need to use the correct Trino Python client. There was a recent addition to create the [Trino sqlalchemy project for superset](https://pypi.org/project/sqlalchemy-trino/). This project comes with a warning that it has not been tested thoroughly yet but could likely be used here as well.

**Comment by bitsondatadev** [comment]
I'm going to post this on the Trino page to see if anyone is interested in picking this up on our end.

**Comment by czgu** [comment]
Hi Brian, for the long-term support of Trino, we could use pyhive https://github.com/dropbox/PyHive for the Querybook integration. That way we can support both query engines with the same integrations. However, it seems that they haven't updated Pypi yet, so I can update the docs to recommend users to use the sqlalchemy-trino package for now

**Comment by bitsondatadev** [comment]
We don't officially support PyHive and there is limited compatibility. I would like to keep this open as this will keep support aválenle from the Trino team.

**Comment by mosabua** [comment]
PyHive seems like a bad idea to use since it basically wraps Hive QL. While this is similar to SQL it is NOT really compatible so it will only sort of work at best. I strongly suggest to use some library that is actually suitable for SQL. 

In the case of Python that would the be the standard implementation of the Python dbapi for Trino, which is the trino-python-client. And it is already used by SQLAlchemy as well. If you have any other driver support that uses either of these the Trino support could be very easy to implement.

**Comment by bitsondatadev** [comment]
@czgu thanks for reopening this. I posted on our site and we have a couple people that are interested in working on this.

**Comment by czgu** [comment]
Hi Brian and Manfred, I checked the trino-python-client and it does support cancel query/getting progress which is everything we need for Querybook integration. If you have any questions regarding the query engine implement feel free to reach out to me here on our slack.

**Comment by bitsondatadev** [comment]
@czgu let me follow up with our community to see if anyone knows of a way to do this or if we can get this implemented to support this.

**Comment by bitsondatadev** [comment]
Will do! Thank you @czgu!

**Comment by shivammmmm** [comment]
Hey Folks !
I'm picking up this issue and will be working on the same. notifying here so that others are aware and will avoid duplicating work.

**Comment by mosabua** [comment]
Awesome news! Looking forward to see your progress.

**Comment by bitsondatadev** [comment]
Wonderful @shivammmmm! Be sure to use the Trino sql alchemy library and not PyHive as noted above please. We want to use the Trino supported Python library.

**Comment by shivammmmm** [comment]
@sandeep-devarapalli @mosabua @bitsondatadev New integration is merged now, We can close this issue now.

**Comment by bitsondatadev** [comment]
> @sandeep-devarapalli @mosabua @bitsondatadev New integration is merged now, We can close this issue now.

Great work @shivammmmm!!!

Linking the merged PR for reference: https://github.com/pinterest/querybook/pull/681

**Comment by mosabua** [comment]
Very nice! Well done!
