### ISSUE TITLE
Helm Chart for Querybook

### ISSUE THREAD

**Issue by yongchand** [pinterest/querybook#562]
Is there any plans to support helm chart for querybook?
If nobody is planning for such, I am willing to contribute!
Also, when will Pinterest upload querybook image to docker hub?
Would be more than happy to actively contribute and also utilize querybook in production level :)

**Comment by czgu** [comment]
Hi Yongchan, it would be great if you want to work on Helm chart solution!
As for the dockerhub, I will contact the the open source community at Pinterest to see how to support that. I will post updates in #535

**Comment by yongchand** [comment]
Thank you so much @czgu! I am looking forward for the updates :)
