### ISSUE TITLE
Load Balancer for web-service.yaml?

### ISSUE THREAD

**Issue by yongchand** [pinterest/querybook#564]
I found out that in web-service.yaml in k8s folder,
`
spec:
    type: LoadBalancer
    ports:
        - protocol: 'TCP'
          port: 80
          targetPort: 10001
    selector:
        app: web
`
the type of service was defined as LoadBalancer, instead of ClusterIP.
Is there any specific reasons why LoadBalancer is chosen instead of ClusterIP?
For production, I personally prefer using ClusterIP and add ingress later, and many open sources (at least for helm charts) use ClusterIP for service.
Do you mind if I can change this to ClusterIP?
If not, is it okay if I can at least use ClusterIP for Querybook Helm Chart?

Reference: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

++ I know load balancer can let service to get exposed, but users can use their own ingress if necessary. I am not sure if exposing externally is a great idea for production level

**Comment by czgu** [comment]
Hi Yongchan. I think I chose load balancer just to get it work, so feel free to change it to use clusterIP 👍
