### ISSUE TITLE
Question about searching users?

### ISSUE THREAD

**Issue by yongchand** [pinterest/querybook#570]
![capture_error](https://user-images.githubusercontent.com/43336767/123431930-c8ae2000-d604-11eb-8c55-a51e5bbcf701.PNG)

Hi, I found out that I cannot search users even though they are actually registered.
This makes me struggle to add users in private DataDoc.
I used default method of registration.
Did anyone encountered this problem previously?
I used k8s file provided to start querybook, and also I found out that user existed in both ES and MySQL backend.

**Comment by czgu** [comment]
Hi Yongchan, I tried it locally and it works. There is a bit of delay (~1 min) between user creation and them showing up on the search index. Can you check if elasticsearch is working correctly on k8s and all search indices are created?

**Comment by yongchand** [comment]
` /opt/querybook/querybook/server/datasources/search.py - INFO "RequestError(400, 'search_phase_execution_exception', 'no mapping found for field [suggest]')"`

I got following error - please let me know if you encountered such before.

**Comment by yongchand** [comment]
@czgu Just found out that it works well with normal MySQL backend -- I should have waited longer. The problem is that same issue is happening when I change MySQL backend to RDS. Will it not work for RDS backend?

**Comment by yongchand** [comment]
Just found out that it works well with normal MySQL backend -- I should have waited longer. The problem is that same issue is happening when I change MySQL backend to RDS. Will it not work for RDS backend?

Fix: It worked after restarting ES and Web pod. I am wondering if this might be some issue with initialization order and connection.

**Comment by czgu** [comment]
oh interesting, I have never tried it on k8s with rds. It would be useful if you can provide stack traces or error logs

**Comment by yongchand** [comment]
Not sure about this still -- but based on what I have been testing I found out that it maybe caused due to configuration time? I may have logged in too fast to web before configuration completed for both web and elasticsearch. Will figure out and comment later.
