### ISSUE TITLE
How to completely remove querybook

### ISSUE THREAD

**Issue by shoyip** [pinterest/querybook#581]
Hello! Newbie alert.
I have recently installed querybook by using `make`, but due to some difficulties I had to remove it afterwards. I have deleted the containers and run `make clean`, but it seems that a lot of the files / libraries that have been installed are still there. Can someone help me to understand what could be taking up so much space (nearly 7GB...)? Thanks in advance!

**Comment by czgu** [comment]
make clean should have removed all your containers. You can also delete the node_modules and virtualenv (Although I am not sure if those are installed) which is another 1.5GB. Where do you see the 7GB count?

**Comment by shoyip** [comment]
Hi! Thanks for your concern! I monitor my free space with `df`, and that's how I saw that the querybook installation had eaten up 7GB. I have tried to remove the folder (hence all the node modules and venvs) but nothing changed so far. I guess the make script has installed things globally, but I cannot find the locations of binaries and libraries that have been installed.
