### ISSUE TITLE
Strings containing commas not rendered correctly

### ISSUE THREAD

**Issue by akizminet** [pinterest/querybook#599]
Hello Querybook team,
I think it is a bug when Querybook writes query result to the CSV file.
![image](https://user-images.githubusercontent.com/52618539/126270499-693e919c-70d4-4bab-8232-5042db918162.png)

**Comment by czgu** [comment]
Interesting, I can't reproduce it on Presto / Sqlite / Sparksql. For the hive engine you are using, are you using the sqlalchemy executor?

![image](https://user-images.githubusercontent.com/8283407/126371792-ad9b4c31-e664-4431-a9cb-07185dbea538.png)

**Comment by akizminet** [comment]
I think the problem is I use `file` for the result store (sorry, I did not mention it in the first message). I see this code in file_store.py
https://github.com/pinterest/querybook/blob/667fda4953ac8c634aace68724b6f7cfef1f1a96/querybook/server/lib/result_store/stores/file_store.py#L37-L39

In `db` mode. `data` doesn't need to split by ","
https://github.com/pinterest/querybook/blob/667fda4953ac8c634aace68724b6f7cfef1f1a96/querybook/server/lib/result_store/stores/db_store.py#L68-L78

**Comment by czgu** [comment]
The fix is merged into master, please let me know if you see any issues. Thanks!

**Comment by akizminet** [comment]
Thank you @czgu. This issue has been fixed.
