### ISSUE TITLE
Keyboard shortcut for auto-formatting a cell's contents

### ISSUE THREAD

**Issue by gandalf013** [pinterest/querybook#633]
I tend to write long queries in querybook's notebook cells and then want to reformat them to look nicer and to spot any weird issues (missing commas, parentheses, etc.).  It would be great to have a keyboard shortcut for this.

**Comment by czgu** [comment]
Hey Alok, there is already a shortcut for auto formatting, you can view the list of shortcuts under `/<env>/info/shortcut/`

![image](https://user-images.githubusercontent.com/8283407/129243112-3e6b034c-6221-4578-9b29-c179882b5875.png)

**Comment by gandalf013** [comment]
Oh, nice!  Should have checked!
