### ISSUE TITLE
Major feature: Support query based search

### ISSUE THREAD

**Issue by czgu** [pinterest/querybook#646]
Story
As a user, I want to go to the exact query cell when searching queries. I also want to check out past executions by me or others.

Requirements:
- We should support filtering by
    - environment (always applied)
        - Note: for adhoc queries, the environment is a multi value field from its associated query engine
    - authors (by default, all users)
    - query engines (by default, all engines in environment)
    - query cell or query execution (by default, both)
    - query type ('SELECT', 'INSERT', 'CREATE', 'DELETE') (by default
    - startTime
    - duration
    - tables in query (we can index by fully qualified name)
- We should support ordering results by
    - recency (default)
    - relevancy
- Once query search is implemented, this should be the first tab in the cmd+k search
- Query search by execution should also be supported in the executions sidebar tab
- Only successful query executions are indexed, however this should be flexible for customization
- We update the search index on the following events
     - update_data_cell
     - delete_data_cell (removal)
     - query_execution_completion
     - query_execution_deletion (removal)
     - Note:  delete_data_cell, query_execution_deletion may be a bulk action such as when removing an archived datadoc or removing all query executions past a certain date. Please ensure the index would update in those cases.

Suggested order for implementation (Separate PR recommended):
- Define the data model in elasticsearch
- Create the pipeline that syncs the data to es
- API to perform query search and the associated cmd+k search UI
- Update to query execution sidebar

**Comment by Aka-shi** [comment]
Can a retention configuration also be included? For example, I would want to only retain 3 months of successful executions instead of indexing all executions since setup. 

Maybe this can be implemented as a separate task which would run periodically once a day. Thoughts?

**Comment by Aka-shi** [comment]
Oh. Didn't know about that. @czgu Yes! this would work for my use case. Thanks!
