### ISSUE TITLE
Question about set OAUTH?

### ISSUE THREAD

**Issue by Happy2017Yao** [pinterest/querybook#653]
I want using oauth from github login in my querybook , and how should I configure the parameters  OAUTH_AUTHORIZATION_URL and OAUTH_TOKEN_URL and OAUTH_USER_PROFILE?

**Comment by Happy2017Yao** [comment]
Anybody have this problem？

**Comment by czgu** [comment]
Hey, the PR above should make this config easier. There are some quirks with github oauth that had to be addressed by code
