### ISSUE TITLE
Document for adding plugin

### ISSUE THREAD

**Issue by mjiangcn** [pinterest/querybook#654]
Hi team,
Is there anyone can share more details or examples how plugins are registered to __init__.py? Especially for new exporters.

**Comment by czgu** [comment]
oh it is a markdown formatting error, it should be `__init__.py`. You can just import the new exporter into that file.

As an example, for python exporter:

```
from lib.export.exporters.python_exporter import PythonExporter
ALL_PLUGIN_EXPORTERS = [
    PythonExporter(),
]
```

**Comment by mjiangcn** [comment]
Thanks @czgu . Just figured it out after looking into the code and tried a few times last week. It worth giving more examples for different plugins in the documents as the way to register is very different for each type of plugin. Like ResultStore is different from Exporter. 
However, it's a very great design to support plugins!

**Comment by czgu** [comment]
Thanks for the feedback! I have since updated the documentation for exporter https://www.querybook.org/docs/integrations/add_exporter, will keep in mind in future when updating other plugins documentations.
