### ISSUE TITLE
[DOC] helm missing in Deployment Guide 

### ISSUE THREAD

**Issue by raphaelauv** [pinterest/querybook#682]
Since https://github.com/pinterest/querybook/pull/576 there is a helm chart , but the doc do not talk about it

Could be nice to have a guide about that helm

Thanks for all your work

**Comment by yongchand** [comment]
@raphaelauv I would add a guide soon :) Thanks

**Comment by jczhong84** [comment]
@raphaelauv @yongchand @okayhooni could any of you help to add some docs about helm chart? thanks!

**Comment by okayhooni** [comment]
yep.. I could do it on next weekend :)

**Comment by yongchand** [comment]
@jczhong84 @okayhooni Sure, now I can share some hand

**Comment by hawkesn** [comment]
I guess this issue can be closed since the guide has been merged?
One thing missing though, is there an external URL we can do `helm pull` from? Is this chart published anywhere?
