### ISSUE TITLE
Full name with Okta auth

### ISSUE THREAD

**Issue by baumandm** [pinterest/querybook#942]
When using the OAuth-based authentication methods, the `username` is repeated as the `fullname`[^1], which doesn't look as nice for users:

```
            user = create_user(
                username=username, fullname=username, email=email, session=session
            )
```

For Okta specifically, this can be fixed by requesting the `profile` scope and using the `name` property, see here:  https://developer.okta.com/docs/reference/api/oidc/#scope-dependent-claims-not-always-returned.

I've tested this out in a custom plugin extending `OktaLoginManager` and overriding the `login_user()` method and it's working well for us. 

Do you see any issues incorporating this natively for anyone using Okta?  If not, I can make a PR.

[^1]: https://github.com/pinterest/querybook/blob/master/querybook/server/app/auth/oauth_auth.py#L136

**Comment by czgu** [comment]
I don't see any issue with this, thanks for adding that!
